-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I
INNER JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY DATEDIFF(DATE_FORMAT(O.DATETIME, '%Y-%m-%d'), DATE_FORMAT(I.DATETIME, '%Y-%m-%d')) DESC
LIMIT 2