-- 코드를 입력하세요
# SELECT CATEGORY, MAX(PRICE) AS 'MAX_PRICE', PRODUCT_NAME
# FROM FOOD_PRODUCT
# GROUP BY CATEGORY
# HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
# ORDER BY PRICE DESC

SELECT PRODUCT_ID, MAX(PRICE), PRODUCT_NAME
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자', '국', '김치', '식용유')